require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EdicaosController do

  # This should return the minimal set of attributes required to create a valid
  # Edicao. As you add validations to Edicao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EdicaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all edicaos as @edicaos" do
      edicao = Edicao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:edicaos).should eq([edicao])
    end
  end

  describe "GET show" do
    it "assigns the requested edicao as @edicao" do
      edicao = Edicao.create! valid_attributes
      get :show, {:id => edicao.to_param}, valid_session
      assigns(:edicao).should eq(edicao)
    end
  end

  describe "GET new" do
    it "assigns a new edicao as @edicao" do
      get :new, {}, valid_session
      assigns(:edicao).should be_a_new(Edicao)
    end
  end

  describe "GET edit" do
    it "assigns the requested edicao as @edicao" do
      edicao = Edicao.create! valid_attributes
      get :edit, {:id => edicao.to_param}, valid_session
      assigns(:edicao).should eq(edicao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Edicao" do
        expect {
          post :create, {:edicao => valid_attributes}, valid_session
        }.to change(Edicao, :count).by(1)
      end

      it "assigns a newly created edicao as @edicao" do
        post :create, {:edicao => valid_attributes}, valid_session
        assigns(:edicao).should be_a(Edicao)
        assigns(:edicao).should be_persisted
      end

      it "redirects to the created edicao" do
        post :create, {:edicao => valid_attributes}, valid_session
        response.should redirect_to(Edicao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved edicao as @edicao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Edicao.any_instance.stub(:save).and_return(false)
        post :create, {:edicao => {}}, valid_session
        assigns(:edicao).should be_a_new(Edicao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Edicao.any_instance.stub(:save).and_return(false)
        post :create, {:edicao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested edicao" do
        edicao = Edicao.create! valid_attributes
        # Assuming there are no other edicaos in the database, this
        # specifies that the Edicao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Edicao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => edicao.to_param, :edicao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested edicao as @edicao" do
        edicao = Edicao.create! valid_attributes
        put :update, {:id => edicao.to_param, :edicao => valid_attributes}, valid_session
        assigns(:edicao).should eq(edicao)
      end

      it "redirects to the edicao" do
        edicao = Edicao.create! valid_attributes
        put :update, {:id => edicao.to_param, :edicao => valid_attributes}, valid_session
        response.should redirect_to(edicao)
      end
    end

    describe "with invalid params" do
      it "assigns the edicao as @edicao" do
        edicao = Edicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Edicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => edicao.to_param, :edicao => {}}, valid_session
        assigns(:edicao).should eq(edicao)
      end

      it "re-renders the 'edit' template" do
        edicao = Edicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Edicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => edicao.to_param, :edicao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested edicao" do
      edicao = Edicao.create! valid_attributes
      expect {
        delete :destroy, {:id => edicao.to_param}, valid_session
      }.to change(Edicao, :count).by(-1)
    end

    it "redirects to the edicaos list" do
      edicao = Edicao.create! valid_attributes
      delete :destroy, {:id => edicao.to_param}, valid_session
      response.should redirect_to(edicaos_url)
    end
  end

end
