require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PathoxracasController do

  # This should return the minimal set of attributes required to create a valid
  # Pathoxraca. As you add validations to Pathoxraca, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PathoxracasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pathoxracas as @pathoxracas" do
      pathoxraca = Pathoxraca.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pathoxracas).should eq([pathoxraca])
    end
  end

  describe "GET show" do
    it "assigns the requested pathoxraca as @pathoxraca" do
      pathoxraca = Pathoxraca.create! valid_attributes
      get :show, {:id => pathoxraca.to_param}, valid_session
      assigns(:pathoxraca).should eq(pathoxraca)
    end
  end

  describe "GET new" do
    it "assigns a new pathoxraca as @pathoxraca" do
      get :new, {}, valid_session
      assigns(:pathoxraca).should be_a_new(Pathoxraca)
    end
  end

  describe "GET edit" do
    it "assigns the requested pathoxraca as @pathoxraca" do
      pathoxraca = Pathoxraca.create! valid_attributes
      get :edit, {:id => pathoxraca.to_param}, valid_session
      assigns(:pathoxraca).should eq(pathoxraca)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pathoxraca" do
        expect {
          post :create, {:pathoxraca => valid_attributes}, valid_session
        }.to change(Pathoxraca, :count).by(1)
      end

      it "assigns a newly created pathoxraca as @pathoxraca" do
        post :create, {:pathoxraca => valid_attributes}, valid_session
        assigns(:pathoxraca).should be_a(Pathoxraca)
        assigns(:pathoxraca).should be_persisted
      end

      it "redirects to the created pathoxraca" do
        post :create, {:pathoxraca => valid_attributes}, valid_session
        response.should redirect_to(Pathoxraca.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pathoxraca as @pathoxraca" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pathoxraca.any_instance.stub(:save).and_return(false)
        post :create, {:pathoxraca => {}}, valid_session
        assigns(:pathoxraca).should be_a_new(Pathoxraca)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pathoxraca.any_instance.stub(:save).and_return(false)
        post :create, {:pathoxraca => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pathoxraca" do
        pathoxraca = Pathoxraca.create! valid_attributes
        # Assuming there are no other pathoxracas in the database, this
        # specifies that the Pathoxraca created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pathoxraca.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => pathoxraca.to_param, :pathoxraca => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested pathoxraca as @pathoxraca" do
        pathoxraca = Pathoxraca.create! valid_attributes
        put :update, {:id => pathoxraca.to_param, :pathoxraca => valid_attributes}, valid_session
        assigns(:pathoxraca).should eq(pathoxraca)
      end

      it "redirects to the pathoxraca" do
        pathoxraca = Pathoxraca.create! valid_attributes
        put :update, {:id => pathoxraca.to_param, :pathoxraca => valid_attributes}, valid_session
        response.should redirect_to(pathoxraca)
      end
    end

    describe "with invalid params" do
      it "assigns the pathoxraca as @pathoxraca" do
        pathoxraca = Pathoxraca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pathoxraca.any_instance.stub(:save).and_return(false)
        put :update, {:id => pathoxraca.to_param, :pathoxraca => {}}, valid_session
        assigns(:pathoxraca).should eq(pathoxraca)
      end

      it "re-renders the 'edit' template" do
        pathoxraca = Pathoxraca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pathoxraca.any_instance.stub(:save).and_return(false)
        put :update, {:id => pathoxraca.to_param, :pathoxraca => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pathoxraca" do
      pathoxraca = Pathoxraca.create! valid_attributes
      expect {
        delete :destroy, {:id => pathoxraca.to_param}, valid_session
      }.to change(Pathoxraca, :count).by(-1)
    end

    it "redirects to the pathoxracas list" do
      pathoxraca = Pathoxraca.create! valid_attributes
      delete :destroy, {:id => pathoxraca.to_param}, valid_session
      response.should redirect_to(pathoxracas_url)
    end
  end

end
