require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RacasController do

  # This should return the minimal set of attributes required to create a valid
  # Raca. As you add validations to Raca, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RacasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all racas as @racas" do
      raca = Raca.create! valid_attributes
      get :index, {}, valid_session
      assigns(:racas).should eq([raca])
    end
  end

  describe "GET show" do
    it "assigns the requested raca as @raca" do
      raca = Raca.create! valid_attributes
      get :show, {:id => raca.to_param}, valid_session
      assigns(:raca).should eq(raca)
    end
  end

  describe "GET new" do
    it "assigns a new raca as @raca" do
      get :new, {}, valid_session
      assigns(:raca).should be_a_new(Raca)
    end
  end

  describe "GET edit" do
    it "assigns the requested raca as @raca" do
      raca = Raca.create! valid_attributes
      get :edit, {:id => raca.to_param}, valid_session
      assigns(:raca).should eq(raca)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Raca" do
        expect {
          post :create, {:raca => valid_attributes}, valid_session
        }.to change(Raca, :count).by(1)
      end

      it "assigns a newly created raca as @raca" do
        post :create, {:raca => valid_attributes}, valid_session
        assigns(:raca).should be_a(Raca)
        assigns(:raca).should be_persisted
      end

      it "redirects to the created raca" do
        post :create, {:raca => valid_attributes}, valid_session
        response.should redirect_to(Raca.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved raca as @raca" do
        # Trigger the behavior that occurs when invalid params are submitted
        Raca.any_instance.stub(:save).and_return(false)
        post :create, {:raca => {}}, valid_session
        assigns(:raca).should be_a_new(Raca)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Raca.any_instance.stub(:save).and_return(false)
        post :create, {:raca => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested raca" do
        raca = Raca.create! valid_attributes
        # Assuming there are no other racas in the database, this
        # specifies that the Raca created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Raca.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => raca.to_param, :raca => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested raca as @raca" do
        raca = Raca.create! valid_attributes
        put :update, {:id => raca.to_param, :raca => valid_attributes}, valid_session
        assigns(:raca).should eq(raca)
      end

      it "redirects to the raca" do
        raca = Raca.create! valid_attributes
        put :update, {:id => raca.to_param, :raca => valid_attributes}, valid_session
        response.should redirect_to(raca)
      end
    end

    describe "with invalid params" do
      it "assigns the raca as @raca" do
        raca = Raca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Raca.any_instance.stub(:save).and_return(false)
        put :update, {:id => raca.to_param, :raca => {}}, valid_session
        assigns(:raca).should eq(raca)
      end

      it "re-renders the 'edit' template" do
        raca = Raca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Raca.any_instance.stub(:save).and_return(false)
        put :update, {:id => raca.to_param, :raca => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested raca" do
      raca = Raca.create! valid_attributes
      expect {
        delete :destroy, {:id => raca.to_param}, valid_session
      }.to change(Raca, :count).by(-1)
    end

    it "redirects to the racas list" do
      raca = Raca.create! valid_attributes
      delete :destroy, {:id => raca.to_param}, valid_session
      response.should redirect_to(racas_url)
    end
  end

end
